// dxf_write.go 实现 ASCII DXF 写出（WriteDXF）：将解析后的 Document 导出为
// R2000 风格的 ASCII DXF（HEADER/TABLES/BLOCKS/ENTITIES/EOF 段）。
//
// 组码与值格式严格对齐 LibreDWG out_dxf.c 的输出约定：
//   - 组码行右对齐 3 字符，行尾 CRLF（\r\n）
//   - 浮点（组码 10-59/110-149/210-239/460-469 等）：%0.16G，NaN/Inf 归零，
//     纯整数值追加 ".0"（对齐 dxf_print_rd）
//   - 整数按组码区间定宽：60-79/170-179/270-299/370-409 用 %6i，
//     80-99/420-449 用 %9i，160-169/450-459 用 %12i（对齐 dxf_format）
//   - 句柄（5/330/340 等）：大写十六进制（FMT_H = %PRIX64）
//   - 角度组码 50-54 以度输出（对齐 VALUE_BD 的 rad2deg 分支）
//   - 实体公共头顺序：0 类型 → 5 句柄 → 330 owner → 100 AcDbEntity →
//     [67] → 8 图层 → 62/420 颜色 → 100 子类
//     （对齐 common_entity_handle_data.spec + common_entity_data.spec）
//
// 覆盖实体（与渲染同源的模型空间主力实体）：LINE/CIRCLE/ARC/POINT/ELLIPSE/
// LWPOLYLINE/TEXT/MTEXT/INSERT/ATTRIB/SOLID/TRACE/3DFACE/RAY/XLINE/SPLINE/
// HATCH（含渐变段与种子点）/DIMENSION(7 类)/LEADER/MLINE/
// POLYLINE_2D/3D/PFACE/MESH(含 VERTEX/SEQEND 聚合)/SHAPE/TOLERANCE/
// VIEWPORT/IMAGE/WIPEOUT/REGION/3DSOLID/BODY(SAT 文本)/OLE2FRAME/
// PROXY_ENTITY。已知取舍：ACIS SAB（version=2）无 SAT1 转换器跳过数据段
// （骨架保留）；PROXY class_id/objids 与 OLE oleclient/框对角不在模型中
// 省略；MLEADER 块内容经 ctx 段还原。
//
// 已知限制：解析路径未保留线型名与文字样式名，写出时按固定值合成
// （线型 ByBlock/ByLayer/Continuous、样式 Standard）；图层名/块名/块基点
// 按 layerColors[].name 与 internalObjects[BLOCK_HEADER] 真值写出，缺失时
// 兜底合成（图层 LAYER_<HEX>、块 *B<HEX>、基点 0,0,0）。pre-R13 文档同样
// 按 R2000 风格写出，$ACADVER 输出 AC1015 以保持文件自洽；其图纸空间实体
// 以 67=1 输出且按句柄去重。
package cad

import (
	"bufio"
	"errors"
	"fmt"
	"github.com/unitedrhino/go-cad/internal/container"
	"io"
	"math"
	"strconv"
	"strings"
)

// WriteDXF 将文档导出为 ASCII DXF 写入 w（R2000 风格段结构）。
func WriteDXF(doc *Document, w io.Writer) error {
	if doc == nil {
		return errors.New("cad: 文档为空，无法写出 DXF")
	}
	x := &dxfWriter{
		w:     bufio.NewWriter(w),
		alloc: newDXFHandleAlloc(doc),
		verts: newDXFVertexIndex(doc),
		doc:   doc,
	}
	x.str(999, "Generated by share/cad WriteDXF (LibreDWG out_dxf aligned)")
	x.writeHeader(doc)
	x.writeTables(doc)
	x.writeBlocks(doc)
	// 模型空间实体（含最大块启发式并入的内容）
	x.writeEntities(doc.modelSpaceEntities(), false)
	// pre-R13 图纸空间实体：67=1 标记，按句柄去重避免与模型空间重复
	if len(doc.pspaceSpace) > 0 {
		list := dedupeByHandle(doc.modelSpaceEntities(), doc.pspaceSpace)
		if len(list) > 0 {
			x.str(0, "SECTION")
			x.str(2, "ENTITIES")
			x.writeEntityList(list, true)
			x.str(0, "ENDSEC")
		}
	}
	x.str(0, "EOF")
	x.err = x.w.Flush()
	return x.err
}

// dedupeByHandle 返回 base 中未出现在 prev 句柄集合里的实体（顺序保持）。
func dedupeByHandle(prev, base []any) []any {
	seen := map[uint64]bool{}
	for _, e := range prev {
		if b := entBase(e); b != nil {
			seen[b.handle] = true
		}
	}
	var out []any
	for _, e := range base {
		b := entBase(e)
		if b == nil || seen[b.handle] {
			continue
		}
		seen[b.handle] = true
		out = append(out, e)
	}
	return out
}

// dxfWriter DXF 组码写出器：累计首个错误，后续调用变为空操作。
type dxfWriter struct {
	w     *bufio.Writer
	err   error
	alloc *dxfHandleAlloc
	verts *dxfVertexIndex
	doc   *Document // 真名/块基点消费源（layerColors/internalObjects）
	vpID  uint16    // VIEWPORT 69 组码 id 自增器（R2000+ 口径）
}

// fail 记录首个错误。
func (x *dxfWriter) fail(err error) {
	if x.err == nil {
		x.err = err
	}
}

// code 仅写组码行（"%3d\r\n"）。
func (x *dxfWriter) code(code int) {
	if x.err != nil {
		return
	}
	if _, err := fmt.Fprintf(x.w, "%3d\r\n", code); err != nil {
		x.fail(err)
	}
}

// val 写组码行 + 原样值行。
func (x *dxfWriter) val(code int, val string) {
	x.code(code)
	if x.err != nil {
		return
	}
	if _, err := x.w.WriteString(val); err != nil {
		x.fail(err)
		return
	}
	if _, err := x.w.WriteString("\r\n"); err != nil {
		x.fail(err)
	}
}

// str 写字符串组码：空串按 out_dxf.c VALUE 约定输出 "0"；
// 值内的 CR/LF 展平为空格保证 DXF 值恒单行。
func (x *dxfWriter) str(code int, s string) {
	s = dxfSanitizeText(s)
	if s == "" {
		s = "0"
	}
	x.val(code, s)
}

// dxfSanitizeText 展平字符串中的换行符（DXF 每个组码值必须单行）。
func dxfSanitizeText(s string) string {
	if !strings.ContainsAny(s, "\r\n") {
		return s
	}
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

// flt 写浮点组码：对齐 out_dxf.c 的 dxf_print_rd——
// %0.16G 格式化、NaN/Inf 归零、纯整数值补 ".0"。
func (x *dxfWriter) flt(code int, v float64) {
	x.val(code, dxfFormatFloat(v))
}

// dxfFormatFloat 对齐 LibreDWG（DXF_PRECISION=16）的浮点格式化。
func dxfFormatFloat(v float64) string {
	if math.IsNaN(v) || math.IsInf(v, 0) {
		v = 0 // 错位解码常产生非法值，写出 0 保证 DXF 可读
	}
	s := strconv.FormatFloat(v, 'G', 16, 64)
	t := strings.TrimPrefix(s, "-")
	// C 实现仅对“纯数字”结果补 .0（含指数或特殊值不补）
	if t != "" && !strings.ContainsAny(t, ".Ee") {
		s += ".0"
	}
	return s
}

// int 写整数组码：按组码区间套用 out_dxf.c dxf_format 的定宽格式。
func (x *dxfWriter) int(code int, v int64) {
	width := dxfIntWidth(code)
	if width > 0 {
		x.val(code, fmt.Sprintf("%*d", width, v))
		return
	}
	x.val(code, strconv.FormatInt(v, 10))
}

// dxfIntWidth 组码 → 整数值行宽度（0 为不定宽），对齐 dxf_format。
func dxfIntWidth(code int) int {
	switch {
	case code >= 60 && code < 80, // BS/BL 计数与标志
		code >= 170 && code < 180,
		code >= 270 && code < 300,
		code >= 370 && code < 410,
		code >= 1060 && code <= 1070:
		return 6
	case code >= 80 && code < 100, // BL
		code >= 420 && code < 450, // int32
		code == 1071:
		return 9
	case code >= 160 && code < 170, // BLL
		code >= 450 && code < 460: // long
		return 12
	}
	return 0
}

// hex 写句柄组码：大写十六进制（FMT_H = %PRIX64）。
func (x *dxfWriter) hex(code int, h uint64) {
	x.val(code, strconv.FormatUint(h, 16))
}

// pt3 写 3D 点三行（10/20/30 起按偏移）。
func (x *dxfWriter) pt3(code int, p point3) {
	x.flt(code, p.x)
	x.flt(code+10, p.y)
	x.flt(code+20, p.z)
}

// pt2 写 2D 点两行（10/20 起按偏移）。
func (x *dxfWriter) pt2(code int, p point2) {
	x.flt(code, p.x)
	x.flt(code+10, p.y)
}

// vec3 写方向/挤出向量三行（210/220/230 起按偏移）。
func (x *dxfWriter) vec3(code int, p point3) {
	x.flt(code, p.x)
	x.flt(code+10, p.y)
	x.flt(code+20, p.z)
}

// radDeg 写角度组码（50-54）：弧度 → 度（对齐 VALUE_BD 的 rad2deg 分支）。
func (x *dxfWriter) radDeg(code int, rad float64) {
	x.flt(code, rad2deg(rad))
}

// ---- HEADER 段 ----

// writeHeader HEADER 段：版本、代码页、插入基点与图幅范围。
func (x *dxfWriter) writeHeader(doc *Document) {
	x.str(0, "SECTION")
	x.str(2, "HEADER")

	x.str(9, "$ACADVER")
	x.str(1, dxfTargetVersion(doc))
	x.str(9, "$DWGCODEPAGE")
	x.str(3, dxfCodepageName(doc.codepage))
	x.str(9, "$INSBASE")
	x.pt3(10, point3{})

	minX, minY, maxX, maxY := docBounds(doc)
	x.str(9, "$EXTMIN")
	x.pt3(10, point3{minX, minY, 0})
	x.str(9, "$EXTMAX")
	x.pt3(10, point3{maxX, maxY, 0})

	x.str(0, "ENDSEC")
}

// dxfTargetVersion DXF 的 $ACADVER：R13+ 直接透传源版本（同版式）；
// pre-R13 源无对应现代 DXF 版式，统一写出为 R2000（AC1015）。
func dxfTargetVersion(doc *Document) string {
	if doc.version.PreR13() {
		return "AC1015"
	}
	return doc.version.VerString()
}

// dxfCodepageName 代码页 → DXF 代码页名（31/39 为简体中文 GBK，其余按
// windows-1252 家族处理，与解码口径 decodeCodepage 一致）。
func dxfCodepageName(cp uint16) string {
	switch cp {
	case 31, 39:
		return "ANSI_936"
	default:
		return "ANSI_1252"
	}
}

// docBounds 模型空间（含最大块启发式内容与 INSERT 展开）的 2D 包围盒：
// 复用渲染的 tessellator 展开与鲁棒包围盒（抗错位解码的离群坐标）；
// 空图时返回 (0,0,0,0)。
func docBounds(doc *Document) (minX, minY, maxX, maxY float64) {
	prims := newTessellator(doc).expandAll()
	if len(prims) == 0 {
		return 0, 0, 0, 0
	}
	bb := robustBounds(prims)
	if bb.invalid() {
		return 0, 0, 0, 0
	}
	return bb.minX, bb.minY, bb.maxX, bb.maxY
}

// ---- TABLES 段 ----

// writeTables TABLES 段：LTYPE（内建三件套，必须先于 LAYER）+ LAYER。
// 解析路径未保留符号表名，图层名按句柄合成、颜色取解析结果。
func (x *dxfWriter) writeTables(doc *Document) {
	x.str(0, "SECTION")
	x.str(2, "TABLES")

	// LTYPE 表：ByBlock/ByLayer/Continuous（对齐 dwg2dxf 的内建三件套）
	x.str(0, "TABLE")
	x.str(2, "LTYPE")
	x.hex(5, x.alloc.ltypeTable)
	x.hex(330, 0)
	x.str(100, "AcDbSymbolTable")
	x.int(70, 1)
	x.ltypeRecord(x.alloc.ltypeByBlock, "ByBlock", "")
	x.ltypeRecord(x.alloc.ltypeByLayer, "ByLayer", "")
	x.ltypeRecord(x.alloc.ltypeCont, "Continuous", "Solid line")
	x.str(0, "ENDTAB")

	// LAYER 表：0 层恒存在 + 模型空间引用到的全部图层
	layers := dxfCollectLayers(doc)
	x.str(0, "TABLE")
	x.str(2, "LAYER")
	x.hex(5, x.alloc.layerTable)
	x.hex(330, 0)
	x.str(100, "AcDbSymbolTable")
	x.int(70, int64(len(layers)))
	for _, lr := range layers {
		x.str(0, "LAYER")
		x.hex(5, lr.handle)
		x.hex(330, x.alloc.layerTable)
		x.str(100, "AcDbSymbolTableRecord")
		x.str(100, "AcDbLayerTableRecord")
		x.str(2, lr.name)
		x.int(70, 0)
		// 颜色语义与渲染取色同口径（layerRenderColor）：32 位值低 24 位
		// ≤0xFF 为 ACI 索引形（方法字节 0xC3/0xC1），写 group 62 索引色；
		// >0xFF 才是 RGB 真彩形，写 group 420。索引形误写 420 会把索引
		// 当真彩输出错误颜色（消防图层 ACI 1~8 彩色系实证）。
		if low := lr.trueColor & 0x00FFFFFF; lr.trueColor > 0 && low > 0xFF {
			x.int(420, int64(lr.trueColor))
		} else if lr.index != 0 && lr.index != 256 {
			x.int(62, int64(lr.index))
		} else {
			x.int(62, 7)
		}
		x.str(6, "Continuous")
	}
	x.str(0, "ENDTAB")

	x.str(0, "ENDSEC")
}

// dxfLayerRecord LAYER 表条目。
type dxfLayerRecord struct {
	handle    uint64
	name      string
	index     int64  // ACI 颜色索引（默认 7 白）
	trueColor uint32 // 真彩色（>0 时优先于索引）
}

// dxfLayerName 图层句柄 → 合成名（0 层为 "0"，其余 LAYER_<HEX>）；
// 仅供真名缺失时的兜底，写出侧统一走 dxfWriter.layerName。
func dxfLayerName(h uint64) string {
	if h == 0 {
		return "0"
	}
	return fmt.Sprintf("LAYER_%X", h)
}

// layerName 图层句柄 → 真名：LAYER 表记录解码保存的 name（DWG 扫描/
// 字符串流、JSON name 键、DXF LAYER 表均有）；缺失时按句柄合成。
func (x *dxfWriter) layerName(h uint64) string {
	if lc, ok := x.doc.layerColors[h]; ok && lc.name != "" {
		return lc.name
	}
	return dxfLayerName(h)
}

// dxfBlockRealName 块定义句柄 → BLOCK_HEADER 真名（DWG/JSON/DXF 三来源
// 均经 internalObjects 登记）；缺失返回空串。
func (x *dxfWriter) dxfBlockRealName(h uint64) string {
	if g := x.doc.internalObjects[h]; g != nil {
		if s, ok := g.Field("name").(string); ok {
			return s
		}
	}
	return ""
}

// blockName 块定义句柄 → DXF 块名：真名优先，无则按句柄合成。
func (x *dxfWriter) blockName(h uint64) string {
	if s := x.dxfBlockRealName(h); s != "" {
		return s
	}
	return dxfBlockName(h)
}

// blockBasePoint 块定义句柄 → BLOCK_HEADER 基点（组码 10/20/30）；
// 未解析（含全零）返回原点。JSON 来源的 base_pt 为 []any 数组形态。
func (x *dxfWriter) blockBasePoint(h uint64) point3 {
	g := x.doc.internalObjects[h]
	if g == nil {
		return point3{}
	}
	switch v := g.Field("base_pt").(type) {
	case []float64:
		if len(v) == 3 {
			return point3{v[0], v[1], v[2]}
		}
	case []any:
		if len(v) == 3 {
			x0, _ := v[0].(float64)
			y0, _ := v[1].(float64)
			z0, _ := v[2].(float64)
			return point3{x0, y0, z0}
		}
	}
	return point3{}
}

// dxfCollectLayers 汇总 LAYER 表条目：先保证 0 层，再收解析到的颜色表与
// 实体实际引用的图层句柄。
func dxfCollectLayers(doc *Document) []dxfLayerRecord {
	seen := map[uint64]bool{}
	out := []dxfLayerRecord{{handle: 0, name: "0", index: 7}}
	seen[0] = true
	add := func(h uint64) {
		if seen[h] {
			return
		}
		seen[h] = true
		rec := dxfLayerRecord{handle: h, name: dxfLayerName(h), index: 7}
		if lc, ok := doc.layerColors[h]; ok {
			if lc.name != "" {
				rec.name = lc.name
			}
			if lc.hasTrue {
				rec.trueColor = lc.trueColor & 0x00FFFFFF
			} else if lc.index != 0 {
				rec.index = int64(lc.index)
			}
		}
		out = append(out, rec)
	}
	for h := range doc.layerColors {
		add(h)
	}
	for _, ent := range doc.modelSpaceEntities() {
		if b := entBase(ent); b != nil {
			add(b.layer)
		}
	}
	return out
}

// ltypeRecord 输出单个 LTYPE 表记录（3 描述、72 对齐码 65、73 划线数 0）。
func (x *dxfWriter) ltypeRecord(handle uint64, name, desc string) {
	x.str(0, "LTYPE")
	x.hex(5, handle)
	x.hex(330, x.alloc.ltypeTable)
	x.str(100, "AcDbSymbolTableRecord")
	x.str(100, "AcDbLinetypeTableRecord")
	x.str(2, name)
	x.int(70, 0)
	x.str(3, desc)
	x.int(72, 65)
	x.int(73, 0)
	x.flt(40, 0)
}

// ---- BLOCKS 段 ----

// dxfBlockName 块定义句柄 → 合成块名（INSERT 组码 2 与 BLOCKS 段共用）。
func dxfBlockName(blockHeader uint64) string {
	return fmt.Sprintf("*B%X", blockHeader)
}

// dxfHandleAlloc 合成句柄分配器：从文档最大句柄之后顺序分配，避免与
// 真实句柄空间冲突。保留位依次为模型/图纸空间 BLOCK_RECORD、内建 LTYPE
// 三件套与两张表头；动态位（SEQEND/ENDBLK/*Model_Space 块标记）随后递增。
type dxfHandleAlloc struct {
	next         uint64 // 下一个可分配句柄
	msRecord     uint64 // 模型空间 BLOCK_RECORD（实体 330）
	psRecord     uint64 // 图纸空间 BLOCK_RECORD
	ltypeTable   uint64 // LTYPE 表头
	ltypeByBlock uint64 // 内建线型 ByBlock
	ltypeByLayer uint64 // 内建线型 ByLayer
	ltypeCont    uint64 // 内建线型 Continuous
	layerTable   uint64 // LAYER 表头
}

// newDXFHandleAlloc 扫描全文档实体/属性取最大句柄，并在其后分配保留位
// （封顶防越界）。
func newDXFHandleAlloc(doc *Document) *dxfHandleAlloc {
	maxH := uint64(0)
	bump := func(h uint64) {
		if h > maxH && h < 0xFFFFFF00 {
			maxH = h
		}
	}
	for _, list := range [][]any{doc.modelSpace, doc.pspaceSpace} {
		for _, ent := range list {
			if b := entBase(ent); b != nil {
				bump(b.handle)
			}
		}
	}
	for _, list := range doc.blocks {
		for _, ent := range list {
			if b := entBase(ent); b != nil {
				bump(b.handle)
			}
		}
	}
	for h := range doc.attribs {
		bump(h)
	}
	a := &dxfHandleAlloc{next: maxH}
	a.msRecord = a.take()
	a.psRecord = a.take()
	a.ltypeTable = a.take()
	a.ltypeByBlock = a.take()
	a.ltypeByLayer = a.take()
	a.ltypeCont = a.take()
	a.layerTable = a.take()
	return a
}

// take 分配下一个合成句柄。
func (a *dxfHandleAlloc) take() uint64 {
	a.next++
	return a.next
}

// writeBlocks BLOCKS 段：*Model_Space 空块对 + 各块定义（内容实体）。
// 最大块内容已并入 ENTITIES 段（模型空间启发式）；以 POLYLINE 实体句柄为
// key 的“伪块”（POLYLINE 顶点按 owner 归类产生）跳过——顶点已由
// ENTITIES 段的 POLYLINE 聚合输出，此处再输出会与 POLYLINE 句柄撞车。
func (x *dxfWriter) writeBlocks(doc *Document) {
	x.str(0, "SECTION")
	x.str(2, "BLOCKS")

	// *Model_Space：内容在 ENTITIES 段，块对恒空（对齐 dwg2dxf）
	x.blockBegin(x.alloc.take(), x.alloc.msRecord, "*Model_Space", point3{})
	x.blockEnd(x.alloc.take(), x.alloc.msRecord)

	largest := doc.largestBlockHeader()
	pseudo := dxfPseudoBlockKeys(doc)
	for h, list := range doc.blocks {
		if h == largest || pseudo[h] {
			continue
		}
		// BLOCK 标记实体用合成句柄：blocks key 来自 ownerhandle 归类，
		// 可能与实体句柄撞车；DXF 中 INSERT↔BLOCK 靠名字（组码 2）关联
		x.blockBegin(x.alloc.take(), x.alloc.msRecord, x.blockName(h), x.blockBasePoint(h))
		x.writeEntityList(list, false)
		x.blockEnd(x.alloc.take(), x.alloc.msRecord)
	}

	x.str(0, "ENDSEC")
}

// dxfPseudoBlockKeys 收集“伪块”key：全部 POLYLINE 实体句柄（其顶点在
// 解析归类时以 owner=POLYLINE 句柄落入 blocks 表）。PFACE/MESH 同理——
// 顶点由 ENTITIES 段的 POLYLINE 聚合输出，块段再输出会产生孤立 VERTEX。
func dxfPseudoBlockKeys(doc *Document) map[uint64]bool {
	out := map[uint64]bool{}
	for _, list := range [][]any{doc.modelSpace, doc.pspaceSpace} {
		for _, ent := range list {
			switch ent.(type) {
			case *entPolyline2d, *entPolyline3d, *entPolylinePface, *entPolylineMesh:
				if b := entBase(ent); b != nil {
					out[b.handle] = true
				}
			}
		}
	}
	return out
}

// blockBegin 输出 BLOCK 头（base 为 BLOCK_HEADER 解析基点，组码 10/20/30）。
func (x *dxfWriter) blockBegin(handle, ownerRecord uint64, name string, base point3) {
	x.str(0, "BLOCK")
	x.hex(5, handle)
	x.hex(330, ownerRecord)
	x.str(100, "AcDbEntity")
	x.str(8, "0")
	x.str(100, "AcDbBlockBegin")
	x.str(2, name)
	x.int(70, 0)
	x.pt3(10, base)
	x.str(3, name)
	x.val(1, "")
}

// blockEnd 输出块结束标记。
func (x *dxfWriter) blockEnd(handle, ownerRecord uint64) {
	x.str(0, "ENDBLK")
	x.hex(5, handle)
	x.hex(330, ownerRecord)
	x.str(100, "AcDbEntity")
	x.str(8, "0")
	x.str(100, "AcDbBlockEnd")
}

// ---- ENTITIES 段 ----

// writeEntities ENTITIES 段（含 SECTION/ENDSEC 包夹）。
func (x *dxfWriter) writeEntities(list []any, pspace bool) {
	x.str(0, "SECTION")
	x.str(2, "ENTITIES")
	x.writeEntityList(list, pspace)
	x.str(0, "ENDSEC")
}

// writeEntityList 按序输出实体：先收集 POLYLINE 聚合要吞掉的顶点句柄，
// 主循环跳过孤立顶点/块结构标记（SEQEND 由 POLYLINE 聚合时生成）；
// 同句柄实体只输出首次出现的（对象图重复条目防御，DXF 句柄必须唯一）。
func (x *dxfWriter) writeEntityList(list []any, pspace bool) {
	owned := map[uint64]bool{}
	for _, ent := range list {
		switch e := ent.(type) {
		case *entPolyline2d:
			for _, h := range e.ownedHandles {
				owned[h] = true
			}
		case *entPolyline3d:
			for _, h := range e.ownedHandles {
				owned[h] = true
			}
		case *entPolylineMesh:
			for _, h := range e.ownedHandles {
				owned[h] = true
			}
		}
	}
	seen := map[uint64]bool{}
	for _, ent := range list {
		b := entBase(ent)
		if b == nil {
			continue
		}
		if owned[b.handle] || seen[b.handle] {
			continue // 顶点已由所属 POLYLINE 输出；重复句柄只输出一次
		}
		seen[b.handle] = true
		switch ent.(type) {
		case *entBlockLike, *entVertexPface, *entVertexPfaceFace:
			// 块结构标记由块段/POLYLINE 聚合生成；PFACE 顶点随其 POLYLINE 跳过
			continue
		}
		x.writeEntity(ent, pspace)
	}
}

// entityHead 实体公共头（0/5/330/100 AcDbEntity/[67]/8），record 为 DXF 记录名。
func (x *dxfWriter) entityHead(base *baseEntity, record string, pspace bool) {
	x.str(0, record)
	x.hex(5, base.handle)
	x.hex(330, x.dxfOwnerRecord(base, pspace))
	x.str(100, "AcDbEntity")
	if pspace || base.mode == 1 {
		x.int(67, 1)
	}
	x.str(8, x.layerName(base.layer))
	x.colorWrite(base)
}

// dxfOwnerRecord 实体的 330 归属：块内实体指 BLOCK_HEADER 句柄，
// 图纸/模型空间实体指合成的 BLOCK_RECORD。
func (x *dxfWriter) dxfOwnerRecord(base *baseEntity, pspace bool) uint64 {
	if pspace || base.mode == 1 {
		return x.alloc.psRecord
	}
	if base.mode == 0 && base.owner != 0 {
		return base.owner
	}
	return x.alloc.msRecord
}

// colorWrite 输出实体颜色（true color 420 优先，其次 ACI 62；ByLayer 不输出）。
func (x *dxfWriter) colorWrite(base *baseEntity) {
	if base.color.hasTrue {
		x.int(420, int64(base.color.trueColor&0x00FFFFFF))
		return
	}
	if base.color.hasIndex && base.color.index != 256 {
		x.int(62, int64(base.color.index))
	}
}

// styleWrite 输出文字样式名（组码 7）：解析路径未保留 STYLE 表，恒 Standard。
func (x *dxfWriter) styleWrite() {
	x.str(7, "Standard")
}

// subclass 输出子类标记（组码 100）。
func (x *dxfWriter) subclass(name string) {
	x.str(100, name)
}

// writeEntity 单实体分派写出。
func (x *dxfWriter) writeEntity(ent any, pspace bool) {
	if x.err != nil {
		return
	}
	base := entBase(ent)
	if base == nil {
		return
	}
	switch e := ent.(type) {
	case *entLine:
		x.entityHead(base, "LINE", pspace)
		x.subclass("AcDbLine")
		x.pt3(10, e.start)
		x.pt3(11, e.end)
	case *entCircle:
		x.entityHead(base, "CIRCLE", pspace)
		x.subclass("AcDbCircle")
		x.pt3(10, e.center)
		x.flt(40, e.radius)
	case *entArc:
		x.entityHead(base, "ARC", pspace)
		x.subclass("AcDbCircle")
		x.pt3(10, e.center)
		x.flt(40, e.radius)
		x.subclass("AcDbArc")
		x.radDeg(50, e.angleStart)
		x.radDeg(51, e.angleEnd)
	case *entPoint:
		x.entityHead(base, "POINT", pspace)
		x.subclass("AcDbPoint")
		x.pt3(10, e.location)
		x.radDeg(50, e.rotation)
	case *entEllipse:
		x.entityHead(base, "ELLIPSE", pspace)
		x.subclass("AcDbEllipse")
		x.pt3(10, e.center)
		x.pt3(11, e.majorAxis)
		x.flt(40, e.ratio)
		x.flt(41, e.startAng)
		x.flt(42, e.endAng)
	case *entLwPolyline:
		x.entityHead(base, "LWPOLYLINE", pspace)
		x.subclass("AcDbPolyline")
		x.int(90, int64(len(e.vertices)))
		closed := int64(0)
		if e.isClosedByGeometry() {
			closed = 1
		}
		x.int(70, closed)
		x.flt(43, e.constWidth)
		if e.elevation != 0 {
			x.flt(38, e.elevation)
		}
		if e.thickness != 0 {
			x.flt(39, e.thickness)
		}
		for i, v := range e.vertices {
			x.pt2(10, v)
			if i < len(e.bulges) && e.bulges[i] != 0 {
				x.flt(42, e.bulges[i])
			}
		}
	case *entText:
		x.entityHead(base, "TEXT", pspace)
		x.subclass("AcDbText")
		x.pt3(10, e.insertion)
		x.flt(40, e.height)
		x.str(1, e.text)
		if e.rotation != 0 {
			x.radDeg(50, e.rotation)
		}
		x.styleWrite()
		if e.gen != 0 {
			x.int(71, int64(e.gen))
		}
		if e.hAlign != 0 {
			x.int(72, int64(e.hAlign))
		}
		if e.alignPt != nil {
			x.pt2(11, *e.alignPt)
			x.flt(31, 0)
		} else {
			x.pt2(11, point2{})
			x.flt(31, 0)
		}
		x.subclass("AcDbText") // ACAD 兼容：对齐点后重复一次子类标记
		if e.vAlign != 0 {
			x.int(73, int64(e.vAlign))
		}
	case *entMText:
		x.entityHead(base, "MTEXT", pspace)
		x.subclass("AcDbMText")
		x.pt3(10, e.insertion)
		x.pt3(11, e.xAxisDir)
		x.flt(40, e.textHeight)
		x.flt(41, e.rectWidth)
		x.int(71, int64(e.attachment))
		x.dxfLongText(e.text)
		x.styleWrite()
	case *entInsert:
		x.entityHead(base, "INSERT", pspace)
		x.subclass("AcDbBlockReference")
		x.str(2, x.blockName(e.blockHeader))
		x.pt3(10, e.position)
		x.flt(41, e.scale.x)
		x.flt(42, e.scale.y)
		x.flt(43, e.scale.z)
		x.radDeg(50, e.rotation)
	case *entAttrib:
		x.entityHead(base, "ATTRIB", pspace)
		x.subclass("AcDbAttribute")
		x.pt3(10, e.insertion)
		x.flt(40, e.height)
		x.str(2, e.tag)
		x.str(1, e.text)
		if e.rotation != 0 {
			x.radDeg(50, e.rotation)
		}
		x.styleWrite()
		if e.gen != 0 {
			x.int(71, int64(e.gen))
		}
		if e.hAlign != 0 {
			x.int(72, int64(e.hAlign))
		}
		if e.vAlign != 0 {
			x.int(74, int64(e.vAlign))
		}
	case *entSolid:
		record := "SOLID"
		if e.trace {
			record = "TRACE"
		}
		x.entityHead(base, record, pspace)
		x.subclass("AcDbTrace")
		if e.elevation != 0 {
			x.flt(38, e.elevation)
		}
		if e.thickness != 0 {
			x.flt(39, e.thickness)
		}
		x.pt2(10, e.p1)
		x.pt2(11, e.p2)
		x.pt2(12, e.p3)
		x.pt2(13, e.p4)
		x.vec3(210, e.extrusion)
	case *entFace3d:
		x.entityHead(base, "3DFACE", pspace)
		x.subclass("AcDbFace")
		x.pt3(10, e.p1)
		x.pt3(11, e.p2)
		x.pt3(12, e.p3)
		x.pt3(13, e.p4)
		if e.invisibleEdgeFlags != 0 {
			x.int(70, int64(e.invisibleEdgeFlags))
		}
	case *entRay:
		record := "RAY"
		sub := "AcDbRay"
		if e.xline {
			record = "XLINE"
			sub = "AcDbXline"
		}
		x.entityHead(base, record, pspace)
		x.subclass(sub)
		x.pt3(10, e.start)
		x.pt3(11, e.unitVector)
	case *entSpline:
		x.entityHead(base, "SPLINE", pspace)
		x.subclass("AcDbSpline")
		x.vec3(210, point3{0, 0, 1})
		flag := int64(0)
		if e.closed {
			flag |= 1
		}
		if e.periodic {
			flag |= 2
		}
		if e.rational {
			flag |= 4
		}
		x.int(70, flag)
		x.int(71, int64(e.degree))
		x.int(72, int64(len(e.knots)))
		x.int(73, int64(len(e.controlPoints)))
		x.int(74, int64(len(e.fitPoints)))
		if e.fitTolerance != 0 {
			x.flt(42, e.fitTolerance)
		}
		if e.knotTolerance != 0 {
			x.flt(43, e.knotTolerance)
		}
		if e.ctrlTolerance != 0 {
			x.flt(44, e.ctrlTolerance)
		}
		for _, k := range e.knots {
			x.flt(40, k)
		}
		for _, w := range e.weights {
			if w != 0 {
				x.flt(41, w)
			}
		}
		for _, p := range e.controlPoints {
			x.pt3(10, p)
		}
		for _, p := range e.fitPoints {
			x.pt3(11, p)
		}
	case *entHatch:
		x.writeHatch(e, pspace)
	case *entDimension:
		x.writeDimension(e, pspace)
	case *entLeader:
		x.entityHead(base, "LEADER", pspace)
		x.subclass("AcDbLeader")
		x.int(73, int64(e.annotationType))
		x.int(72, int64(e.pathType))
		x.int(76, int64(len(e.points)))
		for _, p := range e.points {
			x.pt3(10, p)
		}
	case *entMLine:
		x.entityHead(base, "MLINE", pspace)
		x.subclass("AcDbMline")
		if e.styleHandle != 0 {
			x.hex(340, e.styleHandle)
		}
		x.flt(40, e.scale)
		x.int(70, int64(e.justification))
		x.pt3(10, point3{}) // 基点未解析，输出原点
		x.vec3(210, point3{0, 0, 1})
		x.int(71, int64(e.openClosed))
		x.int(73, int64(e.linesInStyle))
		x.int(72, int64(len(e.vertices)))
		for _, v := range e.vertices {
			x.pt3(11, v.position)
			x.pt3(12, v.direction)
			x.pt3(13, v.miter)
		}
	case *entPolyline2d:
		x.writePolyline2d(e, pspace)
	case *entPolyline3d:
		x.writePolyline3d(e, pspace)
	case *entPolylinePface:
		x.writePolylinePface(e, pspace)
	case *entPolylineMesh:
		x.writePolylineMesh(e, pspace)
	case *entShape:
		x.entityHead(base, "SHAPE", pspace)
		x.subclass("AcDbShape")
		x.pt3(10, e.insertion)
		x.flt(40, e.scale)
		if e.rotation != 0 {
			x.radDeg(50, e.rotation)
		}
		if e.widthFactor != 1 {
			x.flt(41, e.widthFactor)
		}
		if e.oblique != 0 {
			x.radDeg(51, e.oblique)
		}
		if e.thickness != 0 {
			x.flt(39, e.thickness)
		}
		x.vec3(210, e.extrusion)
	case *entTolerance:
		x.entityHead(base, "TOLERANCE", pspace)
		x.subclass("AcDbFcf")
		x.pt3(10, e.insertion)
		x.pt3(11, e.xDirection)
		x.str(1, e.text)
	case *entImage:
		x.writeRasterImage("IMAGE", "AcDbRasterImage", e.classVersion,
			e.pt0, e.uvec, e.vvec, e.imageSize, e.displayProps, e.clipping,
			e.brightness, e.contrast, e.fade, e.clipMode, e.clipBoundaryType,
			e.clipVerts, e.imageDef, e.imageDefReactor, base, pspace)
	case *entWipeout:
		x.writeRasterImage("WIPEOUT", "AcDbWipeout", e.classVersion,
			e.pt0, e.uvec, e.vvec, e.imageSize, e.displayProps, e.clipping,
			e.brightness, e.contrast, e.fade, e.clipMode, e.clipBoundaryType,
			e.clipVerts, e.imageDef, e.imageDefReactor, base, pspace)
	case *entViewport:
		x.writeViewport(e, pspace)
	case *entAcis:
		x.writeAcis(e, pspace)
	case *entOle2Frame:
		x.writeOle2Frame(e, pspace)
	case *entProxyEntity:
		x.writeProxyEntity(e, pspace)
	}
}

// dxfBinaryChunks 二进制组码分块输出（VALUE_BINARY 口径：每行 127 字节、
// 大写十六进制；空数据输出一行空值）。
func (x *dxfWriter) dxfBinaryChunks(code int, data []byte) {
	if len(data) == 0 {
		x.val(code, "")
		return
	}
	for start := 0; start < len(data); start += 127 {
		end := start + 127
		if end > len(data) {
			end = len(data)
		}
		var sb strings.Builder
		for _, b := range data[start:end] {
			sb.WriteString(fmt.Sprintf("%02X", b))
		}
		x.val(code, sb.String())
	}
}

// writeOle2Frame OLE2 框架写出（极限批次 A 补齐）：组码对照 dwg.spec
// DWG_ENTITY (OLE2FRAME) 的 DXF 分支——70 oleversion（恒 2）/10-11 框
// 对角点（宿主 OLE 头未解析，输出原点）/71 类型/72 tile_mode/73
// lock_aspect/90 数据大小/310 二进制块/1 "OLE" 固定标记。oleclient
// （组码 3）依赖 OLE 头解析，省略。
func (x *dxfWriter) writeOle2Frame(e *entOle2Frame, pspace bool) {
	x.entityHead(&e.baseEntity, "OLE2FRAME", pspace)
	x.subclass("AcDbOle2Frame")
	x.int(70, 2)
	x.pt3(10, point3{})
	x.pt3(11, point3{})
	x.int(71, int64(e.oleType))
	x.int(72, int64(e.mode))
	x.int(73, int64(e.lockAspect))
	x.int(90, int64(e.dataSize))
	x.dxfBinaryChunks(310, e.data)
	x.str(1, "OLE")
}

// writeProxyEntity ACAD 代理实体写出（极限批次 A 补齐）：组码对照
// dwg.spec DWG_ENTITY (PROXY_ENTITY) 的 DXF 分支——90 proxy_id/95
// 版本/70 原始数据格式/92+310 代理图形数据/93+310 原始数据位串。
// class_id（91）与 objids 尾表不在本库模型中，省略。
func (x *dxfWriter) writeProxyEntity(e *entProxyEntity, pspace bool) {
	x.entityHead(&e.baseEntity, "PROXY_ENTITY", pspace)
	x.subclass("AcDbProxyEntity")
	x.int(90, int64(e.proxyID))
	version := e.version
	if x.doc != nil && x.doc.version >= container.VerR2018 {
		version = (e.maintVersion << 8) | e.dwgVersionNum
	}
	x.int(95, int64(version))
	x.int(70, boolToInt(e.fromDxf))
	x.int(92, int64(e.proxyDataSize))
	x.dxfBinaryChunks(310, e.proxyData)
	x.int(93, int64(e.dataNumBits))
	x.dxfBinaryChunks(310, e.data)
}

// writeAcis REGION/3DSOLID/BODY 写出（极限批次 A 补齐）：组码对照
// dwg.spec ACTION_3DSOLID 的 DXF 分支（dxf_3dsolid）与 dwgread 实测：
// 290 acis_empty + 70 version（恒 1，DXF 只承载 SAT 文本）+ 组码 1 逐行
// SAT。entAcis.acisData 为解混淆文本，DXF 行须为加密态——按自反变换
// （b≤32 保留、否则 159-b）再加密后输出，行内 '^' 转义为 "^ "（in_dxf
// 读回还原为明文 'A'）。version=2（SAB 二进制）需完整 ACIS 编解码器
// 才能转 SAT1，如实跳过数据段（实体骨架保留）。
func (x *dxfWriter) writeAcis(e *entAcis, pspace bool) {
	record := e.kind
	if record == "" {
		record = "3DSOLID"
	}
	x.entityHead(&e.baseEntity, record, pspace)
	x.subclass("AcDbModelerGeometry")
	x.int(290, boolToInt(e.acisEmpty))
	if e.acisEmpty || e.version == 2 {
		return
	}
	x.int(70, 1)
	for _, line := range strings.Split(string(e.acisData), "\n") {
		line = strings.TrimSuffix(line, "\r")
		if line == "" {
			continue
		}
		enc := acisDeobfuscate([]byte(line))
		enc = []byte(strings.ReplaceAll(string(enc), "^", "^ "))
		for len(enc) > 255 {
			x.val(1, strings.TrimRight(string(enc[:255]), "\x00"))
			enc = enc[255:]
		}
		x.val(1, string(enc))
	}
}

// writeViewport 视口写出（极限批次 A 补齐；组码与顺序对照 dwg.spec
// DWG_ENTITY (VIEWPORT) 的 DXF 分支与 dwgread 实测输出）：10-30 中心/
// 40-41 宽高/68-69 开关与 id/12-15 视图捕捉网格点/16-17 视向与目标/
// 42-45 镜头前后裁剪视高/50-51 角度（度）/72 圆缩放/90 状态/1 样式表/
// 281 渲染模式/71/74 UCS 标志/110-112 UCS 三轴/79 正交视图/146 标高；
// 170 阴影模式与 61 网格主数非零才输出（版本条件组码，对齐 SINCE 分支）。
func (x *dxfWriter) writeViewport(e *entViewport, pspace bool) {
	x.entityHead(&e.baseEntity, "VIEWPORT", pspace)
	x.subclass("AcDbViewport")
	x.pt3(10, e.center)
	x.flt(40, e.width)
	x.flt(41, e.height)
	// 68/69：无归属（owner=0，paperspace 总视口）恒 0；其余 on_off=1、
	// id 按 R2000+ 口径自增（对齐 spec DXF 分支 last_viewport_id）
	onOff, id := 0, 0
	if e.owner != 0 {
		onOff = 1
		x.vpID++
		id = int(x.vpID)
	}
	x.int(68, int64(onOff))
	x.int(69, int64(id))
	x.pt2(12, e.viewCtr)
	x.pt2(13, e.snapBase)
	x.pt2(14, e.snapUnit)
	x.pt2(15, e.gridUnit)
	x.pt3(16, e.viewDir)
	x.pt3(17, e.viewTarget)
	x.flt(42, e.lensLength)
	x.flt(43, e.frontZ)
	x.flt(44, e.backZ)
	x.flt(45, e.viewSize)
	x.radDeg(50, e.snapAng)
	x.radDeg(51, e.viewTwist)
	x.int(72, int64(e.circleZoom))
	x.int(90, int64(e.statusFlag))
	x.val(1, dxfSanitizeText(e.styleSheet))
	x.int(281, int64(e.renderMode))
	x.int(71, boolToInt(e.ucsVP))
	x.int(74, boolToInt(e.ucsAtOrigin))
	x.pt3(110, e.ucsorg)
	x.pt3(111, e.ucsxdir)
	x.pt3(112, e.ucsydir)
	x.int(79, int64(e.ucsOrthoView))
	x.flt(146, e.ucsElevation)
	if e.shadeplotMode != 0 {
		x.int(170, int64(e.shadeplotMode))
	}
	if e.gridMajor != 0 {
		x.int(61, int64(e.gridMajor))
	}
}

// writeRasterImage IMAGE/WIPEOUT 共用写出（位布局同构，仅记录名与子类
// 标记不同）。组码对照 dwg.spec DWG_ENTITY (IMAGE) 的 DXF 分支：
// 90 版本/10-12 三组 3BD/13 图像尺寸 2RD/340 IMAGEDEF/70 显示属性/
// 280 裁剪/281-283 亮度对比淡出/360 IMAGEDEF_REACTOR/71 边界类型/
// 91+14/24 裁剪顶点/290 裁剪模式（R2010+ 才输出，对齐 spec SINCE 分支）。
func (x *dxfWriter) writeRasterImage(record, subclass string, classVersion uint32,
	pt0, uvec, vvec point3, imageSize point2, displayProps uint16, clipping bool,
	brightness, contrast, fade uint8, clipMode uint8, clipBoundaryType uint16,
	clipVerts []point2, imageDef, imageDefReactor uint64, base *baseEntity, pspace bool) {
	x.entityHead(base, record, pspace)
	x.subclass(subclass)
	x.int(90, int64(classVersion))
	x.pt3(10, pt0)
	x.pt3(11, uvec)
	x.pt3(12, vvec)
	x.flt(13, imageSize.x)
	x.flt(23, imageSize.y)
	x.hex(340, imageDef)
	x.int(70, int64(displayProps))
	x.int(280, boolToInt(clipping))
	x.int(281, int64(brightness))
	x.int(282, int64(contrast))
	x.int(283, int64(fade))
	x.hex(360, imageDefReactor)
	x.int(71, int64(clipBoundaryType))
	if clipBoundaryType != 1 {
		x.int(91, int64(len(clipVerts)))
	}
	for _, v := range clipVerts {
		x.flt(14, v.x)
		x.flt(24, v.y)
	}
	if clipMode != 0 && x.doc != nil && x.doc.version >= container.VerR2010 {
		x.int(290, int64(clipMode))
	}
}

// dxfLongText 输出 MTEXT 文本：超 250 字节按 DXF 惯例拆为 3（前段）+ 1（尾段），
// 切分点回退到 UTF-8 字符边界。
func (x *dxfWriter) dxfLongText(text string) {
	const chunk = 250
	b := []byte(text)
	if len(b) <= chunk {
		x.str(1, text)
		return
	}
	cut := chunk
	for cut > 0 && b[cut]&0xC0 == 0x80 {
		cut--
	}
	x.str(3, string(b[:cut]))
	x.str(1, string(b[cut:]))
}

// ---- 多段线聚合 ----

// dxfVertexIndex 全文档 2D/3D 顶点索引（POLYLINE 聚合用）。
type dxfVertexIndex struct {
	v2 map[uint64]*entVertex2d
	v3 map[uint64]*entVertex3d
	// PFACE/MESH 顶点按宿主句柄分组（entVertexPface 定位顶点 +
	// entVertexPfaceFace 面记录），与 vpAll 句柄索引互为补充
	vp    map[uint64][]any
	vpAll map[uint64]any
}

// newDXFVertexIndex 收集模型空间/块/图纸空间全部顶点实体。
func newDXFVertexIndex(doc *Document) *dxfVertexIndex {
	idx := &dxfVertexIndex{
		v2:    map[uint64]*entVertex2d{},
		v3:    map[uint64]*entVertex3d{},
		vp:    map[uint64][]any{},
		vpAll: map[uint64]any{},
	}
	add := func(list []any) {
		for _, e := range list {
			switch t := e.(type) {
			case *entVertex2d:
				idx.v2[t.handle] = t
			case *entVertex3d:
				idx.v3[t.handle] = t
			case *entVertexPface:
				if t.owner != 0 {
					idx.vp[t.owner] = append(idx.vp[t.owner], t)
				}
				idx.vpAll[t.handle] = t
			case *entVertexPfaceFace:
				if t.owner != 0 {
					idx.vp[t.owner] = append(idx.vp[t.owner], t)
				}
				idx.vpAll[t.handle] = t
			}
		}
	}
	add(doc.modelSpace)
	add(doc.pspaceSpace)
	for _, list := range doc.blocks {
		add(list)
	}
	return idx
}

// writePolyline2d 二维多段线：POLYLINE 头 + VERTEX 序列 + SEQEND。
func (x *dxfWriter) writePolyline2d(e *entPolyline2d, pspace bool) {
	x.entityHead(&e.baseEntity, "POLYLINE", pspace)
	x.subclass("AcDb2dPolyline")
	x.int(66, 1) // 顶点跟随标志
	x.flt(10, 0)
	x.flt(20, 0)
	x.flt(30, e.elevation)
	closed := int64(0)
	if e.flags&2 != 0 {
		closed = 1
	}
	x.int(70, closed)
	if e.thickness != 0 {
		x.flt(39, e.thickness)
	}
	if e.widthStart != 0 {
		x.flt(40, e.widthStart)
	}
	if e.widthEnd != 0 {
		x.flt(41, e.widthEnd)
	}
	for _, h := range e.ownedHandles {
		v, ok := x.verts.v2[h]
		if !ok {
			continue
		}
		x.entityHead(&v.baseEntity, "VERTEX", pspace)
		x.subclass("AcDbVertex")
		x.subclass("AcDb2dVertex")
		x.pt3(10, v.position)
		if v.startWidth != 0 {
			x.flt(40, v.startWidth)
		}
		if v.endWidth != 0 {
			x.flt(41, v.endWidth)
		}
		if v.bulge != 0 {
			x.flt(42, v.bulge)
		}
		x.int(70, int64(v.flags))
	}
	x.seqend(pspace)
}

// writePolyline3d 三维多段线：POLYLINE 头（70 恒含 8=3D 位）+ VERTEX（70=32）+ SEQEND。
func (x *dxfWriter) writePolyline3d(e *entPolyline3d, pspace bool) {
	x.entityHead(&e.baseEntity, "POLYLINE", pspace)
	x.subclass("AcDb3dPolyline")
	x.int(66, 1)
	x.flt(10, 0)
	x.flt(20, 0)
	x.flt(30, 0)
	flag := int64(8)
	if e.flags70&1 != 0 {
		flag |= 1
	}
	x.int(70, flag)
	for _, h := range e.ownedHandles {
		v, ok := x.verts.v3[h]
		if !ok {
			continue
		}
		x.entityHead(&v.baseEntity, "VERTEX", pspace)
		x.subclass("AcDbVertex")
		x.subclass("AcDb3dPolylineVertex")
		x.pt3(10, v.position)
		x.int(70, 32)
	}
	x.seqend(pspace)
}

// writePolylinePface 面网格多段线（极限批次 A 补齐）：POLYLINE 头
// （70=64 + 71/72 顶点/面计数）+ 定位顶点（AcDbPolyFaceMeshVertex，
// 70=流内 flag，DWG 实测 192）+ 面记录（AcDbFaceRecord，70=128 +
// 71-74 顶点索引）+ SEQEND。顶点实体按 owner 归属分组消费，组码对照
// dwg.spec POLYLINE_PFACE/VERTEX_PFACE/VERTEX_PFACE_FACE 的 DXF 分支。
func (x *dxfWriter) writePolylinePface(e *entPolylinePface, pspace bool) {
	x.entityHead(&e.baseEntity, "POLYLINE", pspace)
	x.subclass("AcDbPolyFaceMesh")
	x.int(66, 1)
	x.flt(10, 0)
	x.flt(20, 0)
	x.flt(30, 0)
	x.int(70, 64)
	x.int(71, int64(e.numVertices))
	x.int(72, int64(e.numFaces))
	for _, v := range x.verts.vp[e.handle] {
		switch t := v.(type) {
		case *entVertexPface:
			x.entityHead(&t.baseEntity, "VERTEX", pspace)
			x.subclass("AcDbVertex")
			x.subclass("AcDbPolyFaceMeshVertex")
			x.pt3(10, t.position)
			x.int(70, int64(t.flag))
		case *entVertexPfaceFace:
			x.entityHead(&t.baseEntity, "VERTEX", pspace)
			x.subclass("AcDbVertex")
			x.subclass("AcDbFaceRecord")
			x.pt3(10, point3{})
			x.int(70, 128)
			x.int(71, int64(t.vertind[0]))
			x.int(72, int64(t.vertind[1]))
			x.int(73, int64(t.vertind[2]))
			x.int(74, int64(t.vertind[3]))
		}
	}
	x.seqend(pspace)
}

// writePolylineMesh 多面网格（极限批次 A 补齐）：POLYLINE 头（70=16 +
// 71-75 M/N 顶点数与密度、曲面类型）+ VERTEX（AcDbPolyFaceMeshVertex，
// 按 ownedHandles 顺序展开）+ SEQEND。组码对照 dwg.spec POLYLINE_MESH
// 的 DXF 分支（closed 位并入 flag 低位）。
func (x *dxfWriter) writePolylineMesh(e *entPolylineMesh, pspace bool) {
	x.entityHead(&e.baseEntity, "POLYLINE", pspace)
	x.subclass("AcDbPolygonMesh")
	x.int(66, 1)
	x.flt(10, 0)
	x.flt(20, 0)
	x.flt(30, 0)
	flag := int64(16)
	if e.flags&1 != 0 {
		flag |= 1
	}
	x.int(70, flag)
	x.int(71, int64(e.mVertexCount))
	x.int(72, int64(e.nVertexCount))
	x.int(73, int64(e.mDensity))
	x.int(74, int64(e.nDensity))
	x.int(75, int64(e.curveType))
	for _, h := range e.ownedHandles {
		switch t := x.verts.vpAll[h].(type) {
		case *entVertexPface:
			x.entityHead(&t.baseEntity, "VERTEX", pspace)
			x.subclass("AcDbVertex")
			x.subclass("AcDbPolyFaceMeshVertex")
			x.pt3(10, t.position)
			x.int(70, int64(t.flag))
		case *entVertexPfaceFace:
			x.entityHead(&t.baseEntity, "VERTEX", pspace)
			x.subclass("AcDbVertex")
			x.subclass("AcDbFaceRecord")
			x.pt3(10, point3{})
			x.int(70, 128)
			x.int(71, int64(t.vertind[0]))
			x.int(72, int64(t.vertind[1]))
			x.int(73, int64(t.vertind[2]))
			x.int(74, int64(t.vertind[3]))
		}
	}
	x.seqend(pspace)
}

// seqend 输出 POLYLINE 的 SEQEND（合成句柄；模型空间记录归属）。
func (x *dxfWriter) seqend(pspace bool) {
	record := x.alloc.msRecord
	if pspace {
		record = x.alloc.psRecord
	}
	x.str(0, "SEQEND")
	x.hex(5, x.alloc.take())
	x.hex(330, record)
	x.str(100, "AcDbEntity")
	x.str(8, "0")
}

// ---- HATCH ----

// writeHatch 输出填充：边界路径统一按“多段线路径”形式（渲染同源的细分
// 点列）写出；图案定义按解析结果输出（solidFill 时读者无需图案段）。
// 组码顺序对齐 dwg.spec 的 DXF 分支：92(bit1=polyline)/72/73/93/10+20/97，
// 尾随 75/76 与图案段 52/41/77/78/53/43/44/45/46/79/49。
func (x *dxfWriter) writeHatch(e *entHatch, pspace bool) {
	x.entityHead(&e.baseEntity, "HATCH", pspace)
	x.subclass("AcDbHatch")
	x.flt(10, 0)
	x.flt(20, 0)
	x.flt(30, e.elevation)
	x.vec3(210, e.extrusion)
	if e.solidFill {
		x.str(2, "SOLID")
	} else {
		x.str(2, e.name)
	}
	x.int(70, boolToInt(e.solidFill))
	x.int(71, boolToInt(e.associative))
	x.int(91, int64(len(e.paths)))
	for _, p := range e.paths {
		// LibreDWG 以 bit1 判定 polyline 路径（非 DXF 文档的 bit0）；
		// 清 bit2（derived）避免读者期待随后的 47 pixel_size
		x.int(92, (int64(p.flag)|2)&^4)
		x.int(72, 0) // bulges_present=0：细分点列不携带 bulge
		x.int(73, boolToInt(p.closed))
		x.int(93, int64(len(p.points)))
		for _, v := range p.points {
			x.pt2(10, v)
		}
		x.int(97, 0) // 源边界对象数
	}
	x.int(75, int64(e.style))
	x.int(76, int64(e.patternType))
	if !e.solidFill {
		x.flt(52, e.angle)
		if e.scaleSpacing != 1 {
			x.flt(41, e.scaleSpacing)
		}
		x.int(77, boolToInt(e.doubleFlag))
		x.int(78, int64(len(e.deflines)))
		for _, d := range e.deflines {
			// 2BD_1 组码：y 值组码为 x 组码 +1（43/44、45/46）
			x.flt(53, d.angle)
			x.flt(43, d.pt0.x)
			x.flt(44, d.pt0.y)
			x.flt(45, d.offset.x)
			x.flt(46, d.offset.y)
			x.int(79, int64(len(d.dashes)))
			for _, dash := range d.dashes {
				x.flt(49, dash)
			}
		}
	}
	// 种子点（98 + 10/20）与渐变填充段：极限批次 A 补齐（此前写侧
	// 未建模）。组码与顺序对照 dwg.spec HATCH 主体尾部与
	// _HATCH_gradientfill（out_dxf 同序）：98 → 450/451/460/461/452/
	// 462/453/463+63/421 逐色 → 470。
	x.int(98, int64(len(e.seeds)))
	for _, s := range e.seeds {
		x.pt2(10, s)
	}
	if e.isGradientFill != 0 {
		x.int(450, int64(e.isGradientFill))
		x.int(451, int64(e.reserved))
		x.radDeg(460, e.gradientAngle) // 模型侧弧度 → DXF 度
		x.flt(461, e.gradientShift)
		x.int(452, int64(e.singleColorGradient))
		x.flt(462, e.gradientTint)
		x.int(453, int64(len(e.colors)))
		for _, c := range e.colors {
			x.flt(463, c.shiftValue)
			x.int(63, c.colorIndex)
			// CMC rgb 的 method 高字节为 0xc2（真彩无 index 混合）时
			// out_dxf 不输出 421，其余按 63+420-62=421 输出完整 32 位
			if rgb, err := strconv.ParseUint(c.colorRGB, 16, 32); err == nil {
				if rgb>>24 != 0xc2 {
					x.int(421, int64(rgb))
				}
			}
		}
		x.str(470, e.gradientName)
	}
}

// boolToInt 布尔 → DXF 整数（0/1）。
func boolToInt(b bool) int64 {
	if b {
		return 1
	}
	return 0
}

// ---- DIMENSION ----

// dxfDimSubclass 标注 DXF 70 低 3 位类型 → 子类名（与 dimFlag 合成规则对应）。
func dxfDimSubclass(flag uint8) string {
	switch flag & 0x7 {
	case 1:
		return "AcDbAlignedDimension"
	case 2:
		return "AcDb2LineAngularDimension"
	case 3:
		return "AcDbDiametricDimension"
	case 4:
		return "AcDbRadialDimension"
	case 5:
		return "AcDb3PointAngularDimension"
	case 6:
		return "AcDbOrdinateDimension"
	default:
		return "AcDbRotatedDimension"
	}
}

// writeDimension 标注：公共段（AcDbDimension）+ 类型专属子类段。
// 定义点映射与 dxf_cross_test 对齐：非 ANG2LN 的 10=point10；
// ANG2LN 的 10=（point16x,p16y）、16=point10。
func (x *dxfWriter) writeDimension(e *entDimension, pspace bool) {
	sub := dxfDimSubclass(e.dimFlag)
	ang2ln := sub == "AcDb2LineAngularDimension"
	x.entityHead(&e.baseEntity, "DIMENSION", pspace)
	x.subclass("AcDbDimension")
	if ang2ln {
		x.flt(10, e.point16x)
		x.flt(20, e.p16y)
		x.flt(30, 0)
	} else {
		x.pt3(10, e.point10)
	}
	x.pt3(11, e.textMidpoint)
	x.int(70, int64(e.dimFlag))
	if e.userText != "" {
		x.str(1, e.userText)
	}
	if e.attachmentPoint != 0 {
		x.int(71, int64(e.attachmentPoint))
	}
	if e.actualMeasurement != 0 {
		x.flt(42, e.actualMeasurement)
	}
	if e.insertRotation != 0 {
		x.radDeg(54, e.insertRotation)
	}
	if e.horizontalDir != 0 {
		x.radDeg(51, e.horizontalDir)
	}
	if e.textRotation != 0 {
		x.radDeg(53, e.textRotation)
	}
	x.pt3(13, e.point13)
	x.pt3(14, e.point14)

	x.subclass(sub)
	switch sub {
	case "AcDb2LineAngularDimension":
		x.pt3(15, e.point15)
		x.pt3(16, e.point10)
	case "AcDb3PointAngularDimension":
		x.pt3(15, e.point15)
	case "AcDbRotatedDimension", "AcDbAlignedDimension":
		if e.dimRotation != 0 {
			x.radDeg(50, e.dimRotation)
		}
		if e.extLineRotation != 0 {
			x.radDeg(52, e.extLineRotation)
		}
	}
}
